["get", "/posts"]: "posts#index"
["get", "/posts/show"]: "posts#show"
["get", "/posts/delete"]: "posts#delete"
["get", "/posts/new"]: "posts#new"
["post", "/posts/new"]: "posts#create"
["get", "/posts/edit"]: "posts#edit"
["post", "/posts/edit"]: "posts#update"
